### ISSUE TITLE
Data license?

### ISSUE THREAD

**Issue by pombredanne** [fabric8-analytics/cvedb#10924]
Hi:
Following up from https://github.com/fabric8-analytics/cvejob/issues/146 this repo is also missing a license. I would strongly suggest CC0-1.0 for the data https://creativecommons.org/publicdomain/zero/1.0/ as this will make mixing data together much easier and this is the one we use for https://github.com/nexb/vulnerablecode but a license is needed. 
@msrb 
@CermakM 
@tisnik 
I am pinging you since you were also involved with https://github.com/fabric8-analytics/cvejob/issues/146

**Comment by msrb** [comment]
Cc'ing Darshan (@dvandra) as he seems to be maintaining this repository now.

**Comment by pombredanne** [comment]
@dvandra Hi :wave:

**Comment by jasinner** [comment]
This repository looks like it was seeded was data in the victims/victims-cve-db and therefore is bound by the existing license published there:

https://github.com/victims/victims-cve-db/blob/master/cc-by-sa-4.0.txt

**Comment by pombredanne** [comment]
@jasinner Hey! that makes sense! I should know better :) 
What about adding that license file here?

**Comment by msrb** [comment]
@dvandra any luck figuring out what the license should be for this repository? Clear licensing could open doors for collaboration with other parties that are trying to do the same thing. Any license is better than no license :)

**Comment by msrb** [comment]
> This repository looks like it was seeded was data in the victims/victims-cve-db and therefore is bound by the existing license published there:
> 
> https://github.com/victims/victims-cve-db/blob/master/cc-by-sa-4.0.txt

I think I can clarify this. This repo started as a greenfield project and, as far as I remember, the data from upstream victims/victims-cve-db were never merged into it. It uses the same YAML format though.

The decision to use the same YAML format as victims/victims-cve-db was deliberate. When we created this repository and the automation bits around it, I was hoping that we could either contribute what we built here back to the Project Victims at some point (at the beginning we didn't know if the automation will actually work -- it was basically an experiment) and collaborate there, or that we could at least share data between the two projects.

As you might have guessed, these plans never materialized.

**Comment by pombredanne** [comment]
@msrb FWIW, the efforts of @haikoschol and @sbs2001and other contributors are starting to bear fruits in https://github.com/nexb/vulnerablecode  and this will soon be usable :) ... so the sooner we can get license clarity the better.

**Comment by pombredanne** [comment]
And FYI I also presented our plans at the Linux Foundation summit in Austin, TX last month (at least, virtually in Austin ;) ) https://ossna2020.sched.com/event/c46p/why-is-there-no-free-software-vulnerability-database-philippe-ombredanne-aboutcodeorg-and-nexb-inc-michael-herzog-nexb-inc?iframe=no&w=100%&sidebar=yes&bg=no

**Comment by pombredanne** [comment]
Gentle ping :)

**Comment by pombredanne** [comment]
Note that the vulnerabilities database we are putting together is going to be licensed under either CC0 or CC-BY, not CC-BY-SA.
So if you pick CC-BY-SA here you will be able to reuse our data (we are creating code to find new vulnerabilities) BUT we will not be able to include yours

**Comment by pombredanne** [comment]
Well I guess this repo is no longer maintained or updated, so the question about licenses are moot.
It would have been nice to know though. Cheers!
